version: '3.1'
services:
  mysql-master:
    image: mysql:8.0.18
    container_name: mysql-master
    command: --server-id=11
    environment:
      - MYSQL_ROOT_PASSWORD=19811981
    networks:
      - my_net
    ports:
      - 13306:3306
        #restart: always
    volumes:
      - /home/robbie/workspace/mysql/replication/master/datadir:/var/lib/mysql
  mysql-slave:
    image: mysql:8.0.18
    container_name: mysql-slave
    command: --server-id=21
    environment:
      - MYSQL_ROOT_PASSWORD=19811981
    networks:
      - my_net
    ports:
      - 23306:3306
    volumes:
      - /home/robbie/workspace/mysql/replication/slave/datadir:/var/lib/mysql
    depends_on:
      - mysql-master
        #restart: always

networks:
  my_net:
    external: true
