version: '3.1'
services:
  elk-elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elk-elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - my_net
    ports:
      - 9200:9200
      - 9300:9300
        #restart: always
    #volumes:
    #  - /home/robbie/workspace/mysql/replication/master/datadir:/var/lib/mysql
  elk-kibana:
    image: kibana:7.6.2
    container_name: elk-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elk-elasticsearch:9200
      #- JVM_OPTS=-Xmx800m -Xms400m
    networks:
      - my_net
    ports:
      - 5601:5601 
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elk-elasticsearch
        #restart: always
  elk-logstash:
    image: logstash:7.6.2
    container_name: elk-logstash
    environment:
      - MONITORING_LASTICSEARCH_HOSTS=http://elk-elasticsearch:9200     
    volumes:
            #- ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - my_net
    ports:
      - 5044:5044
    depends_on:
      - elk-elasticsearch
       
networks:
  my_net:
    external: true
